### ISSUE TITLE
Error: Cannot find module './pages/itemPage'

### ISSUE THREAD

**Issue by Tamriel** [amelisa/amelisa-crud-example#1]
With `npm start` I get
`> amelisa-crud-example@0.1.0 start /home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example
> concurrent 'nodemon server.js' 'gulp'

"concurrent" command is deprecated, use "concurrently" instead.

[0] [nodemon] 1.11.0
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: /home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/server/**/*
[0] [nodemon] starting `node server.js`
[1] [23:39:54] 
[1] Requiring external module babel-register
[1] [23:39:55] 
[1] Using gulpfile ~/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/gulpfile.babel.js
[1] [23:39:55] 
[1] Starting 'css'...
[1] [23:39:55] 
[1] Finished 'css' after 23 ms
[1] [23:39:55] Starting 'watch'...
[1] [23:39:55] Finished 'watch' after 12 ms
[1] [23:39:55] Starting 'default'...
[1] [23:39:55] Finished 'default' after 32 μs
[0] { Error: Cannot find module './pages/itemPage'
[0]     at Function.Module._resolveFilename (module.js:472:15)
[0]     at Function.Module._load (module.js:420:25)
[0]     at Module.require (module.js:500:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/apps/main/Routes.jsx:5:1)
[0]     at Module._compile (module.js:573:32)
[0]     at loader (/home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/node_modules/babel-register/lib/node.js:144:5)
[0]     at Object.require.extensions.(anonymous function) [as .jsx] (/home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/node_modules/babel-register/lib/node.js:154:7)
[0]     at Module.load (module.js:490:32)
[0]     at tryModuleLoad (module.js:449:12) code: 'MODULE_NOT_FOUND' } 'Error: Cannot find module \'./pages/itemPage\'\n    at Function.Module._resolveFilename (module.js:472:15)\n    at Function.Module._load (module.js:420:25)\n    at Module.require (module.js:500:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/apps/main/Routes.jsx:5:1)\n    at Module._compile (module.js:573:32)\n    at loader (/home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .jsx] (/home/tamriel/Dokumente/Studium/Masterarbeit/Code/amelisa-crud-example/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (module.js:490:32)\n    at tryModuleLoad (module.js:449:12)'
`

**Comment by vmakhaev** [comment]
I've just tried to remove node_modules folder and reinstall it again and `npm start` works properly after this. 
Please, try to clean npm cache and reinstall node_modules. Let me know if it succeed or not.

I'm using node v6.9.1, npm 3.10.8 on mac os.
What os, node, npm do you use?

**Comment by nableru** [comment]
$ uname -r
4.4.26-gentoo-nouveau

 $ node -v
v6.9.1

$rm -rf ~/.npm

$npm cache clear

$ rm -rf node_modules/*

$ npm install
...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN amelisa-crud-example@0.1.0 No description
npm WARN amelisa-crud-example@0.1.0 No repository field.

 $ npm start

> amelisa-crud-example@0.1.0 start /home/kpect/www/amelisa/amelisa-crud-example
> concurrent 'nodemon server.js' 'gulp'

"concurrent" command is deprecated, use "concurrently" instead.

[0] [nodemon] 1.11.0
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: /home/kpect/www/amelisa/amelisa-crud-example/server/**/*
[0] [nodemon] starting `node server.js`
[1] [22:59:32]
[1] Requiring external module babel-register
[1] [22:59:54]
[1] Using gulpfile ~/www/amelisa/amelisa-crud-example/gulpfile.babel.js
[1] [22:59:54]
[1] Starting 'css'...
[1] [22:59:54]
[1] Finished 'css' after 61 ms
[1] [22:59:54]
[1] Starting 'watch'...
[1] [22:59:54]
[1] Finished 'watch' after 41 ms
[1] [22:59:54] Starting 'default'...
[1] [22:59:54]
[1] Finished 'default' after 58 μs
[0] { Error: Cannot find module './pages/itemPage'
[0]     at Function.Module._resolveFilename (module.js:469:15)
[0]     at Function.Module._load (module.js:417:25)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/home/kpect/www/amelisa/amelisa-crud-example/apps/main/Routes.jsx:5:1)
[0]     at Module._compile (module.js:570:32)
[0]     at loader (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:144:5)
[0]     at Object.require.extensions.(anonymous function) [as .jsx] (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:154:7)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' } 'Error: Cannot find module \'./pages/itemPage\'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/home/kpect/www/amelisa/amelisa-crud-example/apps/main/Routes.jsx:5:1)\n    at Module._compile (module.js:570:32)\n    at loader (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .jsx] (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)'
 ^C

 $ node server.js
{ Error: Cannot find module './pages/itemPage'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kpect/www/amelisa/amelisa-crud-example/apps/main/Routes.jsx:5:1)
    at Module._compile (module.js:570:32)
    at loader (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' } 'Error: Cannot find module \'./pages/itemPage\'\n    at Function.Module._resolveFilename (module.js:469:15)\n    at Function.Module._load (module.js:417:25)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/home/kpect/www/amelisa/amelisa-crud-example/apps/main/Routes.jsx:5:1)\n    at Module._compile (module.js:570:32)\n    at loader (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:144:5)\n    at Object.require.extensions.(anonymous function) [as .jsx] (/home/kpect/www/amelisa/amelisa-crud-example/node_modules/babel-register/lib/node.js:154:7)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)'

**Comment by nableru** [comment]
fix: 
~/www/amelisa/amelisa-crud-example/apps/main/pages $ mv ItemPage.jsx itemPage.jsx
$npm start
...
 24826 listening. Go to: http://localhost:3000

**Comment by vmakhaev** [comment]
fixed
